### ISSUE TITLE
Is this mod dead?

### ISSUE THREAD

**Issue by wolvyreen** [gamma1772/Flesh2LeatherFabric#7]
The last update this mod had was in March 2022.

Is this mod dead?

**Comment by mdujovic17** [comment]
No.

**Comment by mdujovic17** [comment]
Just have no time to work on MC mods. I'll update them when I find the time.

**Comment by wolvyreen** [comment]
In my mind, when a modder says "I don't have time to update the mods", to me that means it's useless to the community as the game updates don't wait for modders.

Therefore it is essentially dead for any versions that it does not get updated for when the new versions of the games get released.

People will then move on to an alternative mod and never return to your mod.

I get that you did everyone a favor by giving us the mod etc etc etc but at least don't mislead the community. Maybe someone skilled can take the mod over at least if you could let it go but while you tell everyone that you are still the going to update the mod and then leave it for months before you get to it, is just sad to be honest.

I'm not a modder so I can't unfortunately.

Anyways... Don't take this as though I am not grateful for the times I was able to use the mod.  I'm just saying that I have too many times seen modders hold on to their mods because of not being able to let go and waste the communities time.

stay safe.

**Comment by mdujovic17** [comment]
I am not forcing anyone to use or wait for my mods to get updated. I said I'll update the mod when I find the time, as I am currently busy with my job, university and some other, more important projects.

The codebases of all my mods are licensed under MIT, so anyone is free to port them to any and all versions and mod loaders of Minecraft.

That goes without saying that even if someone decides to port my mods, it doesn't mean I will give up on my mods.
